---

- name: Set up Target Host Networking
  hosts: target-hosts
  roles:
    - configure-networking

# ansible target-hosts -m shell -a "ip addr show" > all-interfaces.txt
# cat all-interfaces.txt | grep -v "$(cat all-interfaces.txt | grep 'lo:' -A 3)"
